version: '3.8'

services:
  nodejsrmelendez:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejsrmelendez
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DB=$MYSQL_DB
    ports:
      - "13500:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-networkrmelendez
    command: ./wait-for db:13500 -- /home/node/app/node_modules/.bin/nodemon app.js

  db_nuevo:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
    volumes:     
      - dbdatarmelendez:/var/lib/mysql
    networks:
      - app-networkrmelendez

networks:
  app-networkrmelendez:
    driver: bridge

volumes:
  dbdatarmelendez:
  node_modules:
